# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd9e364695c3a7b17af1f553937fe308d856e7777ce0b101c1db778cba5dcf92f3dd2e6e9c98093837cbd85f37813d0d822032f7e72e39ec7e4e6ebf1fdc2204

test:
  secret_key_base: 03416dd39f339e89349705132f580957494522813541c3535b9a611dd7ffe832a8deba7b397e660758b4430c38beadf20e82aa7b229deafc7135ac26a5bfbd24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
